spin_manifest_version = 2

[application]
name = "code-social"
version = "0.1.0"
authors = ["ārXāngēl <lavrenyk@gmail.com>"]
description = "Core of the application"

[variables]
db_user = { default = "lavrenyk" }
db_pswd = { default = "kakeepoo" }
db_host = { default = "127.0.0.1" }
db_name = { default = "social" }

[[trigger.http]]
route = "/api/profile/..."
component = "profile-api"

[component.profile-api]
source = "profile-api/target/wasm32-wasi/release/profile_api.wasm"
allowed_outbound_hosts = ["postgres://127.0.0.1:5432"]
[component.profile-api.variables]
db_url = "host={{db_host}} user={{db_user}} password={{db_pswd}} dbname={{db_name}}"
[component.profile-api.build]
command = "cargo build --target wasm32-wasi --release"
workdir = "profile-api"
watch = ["src/**/*.rs", "Cargo.toml"]
